---
name: Deploy Contracts CD for QA

on:
  push:
    branches: [main, PP-675/contracts-cd]

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    environment:
      name: QA

      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "16.x"

        - name: Install dependencies
          run: npm install

        - name: Deploy Contract on Testnet
          run: |
            MNEMONIC=${{ secrets.QA_MNEMONIC }}  npx hardhat deploy --network testnet
            cat contract-addresses.json
