---
name: Deploy Contracts for RIF-Wallet-Mainnet

on:
  push:
    tags:
      - '**stable-rifwallet**'

jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    environment:
      name: RIF-Wallet-Mainnet

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Deploy Contract on Testnet
        run: |
          MNEMONIC='${{ secrets.RWM_MNEMONIC }}'  npx hardhat deploy --network mainnet
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: contract-addresses-rwm.json
          path: contract-addresses.json
