name: CI for RIF-Relay-Contract
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'

            - name: Install dependencies
              run: npm install

            - name: Check Linter bugs for Typescript
              run: npm run lint:ts

            - name: See bugs on solidity
              run: npm run lint:sol

            - name: Check Codestyles errors
              run: npm run prettier

    test:
        runs-on: ubuntu-latest
        needs: [lint]

        steps:
            # Downloads a copy of the code in your repository before running CI tests
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Run docker image
              run: docker run -d -p 127.0.0.1:4444:4444 --name enveloping-rskj antonioiovlabs/rskj:latest --regtest

            # Performs a clean installation of all dependencies in the `package.json` file
            # For more information, see https://docs.npmjs.com/cli/ci.html
            - name: Run contract test
              run: npm run test
